# -*- mode: snippet -*-
# key: __rookie.org
# name: rookie recruiting interview form
# --
+TITLE: `(format-time-string "%Y-%m-%d")` $1

* phase/position/name/route
`(string-join
 (mapcar #'capitalize
         ;; Replace -,_... with space
         (split-string
          (let (case-fold-search)
            ;; Separating lower from upper: hello|World
            (replace-regexp-in-string
             "\\([[:lower:]]\\)\\([[:upper:]]\\)" "\\1 \\2"
             ;; Separating upper from (upper and lower): HTTP|Server
             (replace-regexp-in-string "\\([[:upper:]]\\)\\([[:upper:]][0-9[:lower:]]\\)"
                                       "\\1 \\2" (file-name-base buffer-file-name))))
          "[^[:word:]0-9]+"
          )) " " )
`
- [エンジニア新卒採用基準\_asof181018](https://docs.google.com/document/d/18OfcQjU_hLkB-30HjusIQUZ0Q_3Q9uuwZKt6gjm0nWk/edit)

* アイスブレイク
** 面接官の自己紹介
学生が逆質問をしやすくするため
** 学生の自己紹介
** 今日の流れ（最後に質問時間を設けることを伝える）

* memo
** 【サポート精神・利他心】就活で大切にしている判断基準(軸)は何ですか？⇒誰かのために何かしたい、他者に貢献したい　など 。「自己成長」でもいいが、自分矢印のワードしか出てこないのはよくない

** 【ミッションビジョンへの共感】なぜ freee を受けたのですか？⇒この時点で強く求めているわけではない。「技術的につよそうだと思った」的な内容でも OK。その技術力をどう活かしていきたいか

** 【ユーザー志向、チーム志向】開発（または研究など）に取り組む中で、どういう風に進めていきましたか？なぜ継続して頑張れたと思いますか？どのようなゴール、理想の状態を描いていましたか？チームでの開発経験、共同作業はありますか？⇒ユーザー志向：なぜ継続して頑張れたと思うか？どのようなゴール、理想の状態を描いていたのか？ チーム志向：意見の相違はなかったか？あった際、どのように対応したのか？

**  【成長への貪欲さ】気分が乗らない（気が進まない）事柄でも頑張って取り組んだ経験はありますか？

** 【タイプ別】■ギーク：特にのめり込んだ経験はありますか？⇒程度の確認（飽きっぽくない？）■ガッツ：一番大変な思いをした経験は？⇒行動力、熱意の確認（途中で折れてない？）　■器用：一番大変な思いをした経験は？⇒筋の良さの確認（成果出せた？）
*** ギーク
『開発経験で今まで特にのめり込んだ経験はありますか？無ければ開発経験でなくても大丈夫です』
『一方で、のめり込みすぎて、納期を守れなかったことや、やるべきことをやっていなかったなど視野が狭くなっていたことはないか？また、自身で飽きっぽいと思うことはないか？』
程度の確認

*** ガッツ
『これまでの人生で一番大変な思いをした経験／壁にぶつかった経験はありましたか？』
『一方で、これまでに途中で心が折れた経験はありますか？』
行動力、熱意の確認

*** 器用
『これまでの人生で一番大変な思いをした経験／壁にぶつかった経験はありましたか？』
『最終的に自分が目指した成果は出すことができましたか？』
筋の良さの確認


* memo

** バックグラウンドを知る

*** 大学でやってたこと


** これまでの大学で一番成果出せたなと感じていること


** これまでの大学で一番大変だったこと・苦手なこと


** テンションが上ったこと


** 逆にストレスだと思ったこと


** 技術力を知る

*** どういった言語を経験しているか

*** どういった領域を担当しているか

*** どういったフェーズの製品を担当したか

*** どういった成果物があるか

*** 基礎力があるか

*** 噛み砕いて説明できる

*** 活かせる技術はあるか

*** 業務以外での勉強

*** プログラミングで大切にしてること

*** 自主的にキャッチアップをおこなっているか

*** 今後やりたい技術

*** 技術へのモチベーション

* 1 次評価
** 【人物素養タイプ】ガッツ：質より量、根性ある　器用：地頭や容量が良い　ギーク：技術が好き、技術的に突き抜けそうなタイプ
*** 回答（文章）

** 採用したいか？
採用したいか？
*** 回答（選択肢回答タイプ）
--None--
Yes
No
*** 回答の度合いを教えて下さい
--None--
強く採用したい
採用したい
相談つきで採用したい
採用したくない
強く採用したくない
*** 回答（文章）

** 【最低水準のエンジニアリング素養】プログラミングやそれに類する技術に何らか触れて手を動かしているか　『回答（文章）』には判断した候補者との会話や発言などのファクトを記載してください。
回答の基準値はこちらで選択をお願いします

1=全然だめ
2=厳しい
3=問題ない
4=期待できる
5=期待を大幅に上回る

*** 回答（選択肢回答タイプ）
--None--
*** 回答（文章）

** 【素直さ】フィードバックを受け入れ、実行できるか・言い訳をしないか、環境のせいにしないか　『回答（文章）』には判断した候補者との会話や発言などのファクトを記載してください。
回答の基準値はこちらで選択をお願いします

1=全然だめ
2=厳しい
3=問題ない
4=期待できる
5=期待を大幅に上回る

*** 回答（選択肢回答タイプ）
--None--
*** 回答（文章）

** 【理解力 or キャッチアップ力】今まで触れた技術について本質を理解しているか・学んだことを応用して類似の問題を解決できるか　『回答（文章）』には判断した候補者との会話や発言などのファクトを記載してください。
回答の基準値はこちらで選択をお願いします

1=全然だめ
2=厳しい
3=問題ない
4=期待できる
5=期待を大幅に上回る

*** 回答（選択肢回答タイプ）
--None--
*** 回答（文章）

** 【成長への貪欲さ】仕事を選り好みせずユーザーの価値や自分の成長と捉えられるか・好奇心がありなんでも深く知ろうとするか　『回答（文章）』には判断した候補者との会話や発言などのファクトを記載してください。
回答の基準値はこちらで選択をお願いします

1=全然だめ
2=厳しい
3=問題ない
4=期待できる
5=期待を大幅に上回る

*** 回答（選択肢回答タイプ）
--None--
*** 回答（文章）

** 【あえて共有】自分の成長や成果を周りに共有できるか・１人で抱え込まず、適切なタイミングで人に頼れるか　『回答（文章）』には判断した候補者との会話や発言などのファクトを記載してください。
回答の基準値はこちらで選択をお願いします

1=全然だめ
2=厳しい
3=問題ない
4=期待できる
5=期待を大幅に上回る

*** 回答（選択肢回答タイプ）
--None--
*** 回答（文章）

** 次の面接官へ申し送りがあれば記入おねがいします
次の面接官へ申し送りがあれば記入おねがいします
回答（文章）

** リクルーター（採用チーム）へ申し送りがあれば記入おねがいします
リクルーター（採用チーム）へ申し送りがあれば記入おねがいします
回答（文章）

* 2 次評価
** 採用したいか？
*** 回答（選択肢回答タイプ）
YES
NO
**** 回答（選択肢回答タイプ）
*** 回答の度合いを教えて下さい
強く採用したい
採用したい
相談つきで採用したい
採用したくない
強く採用したくない
**** 回答（選択肢回答タイプ）
*** 回答（文章）
** 【サポート精神・利他心】就活で大切にしている判断基準(軸)は何ですか？⇒誰かのために何かしたい、他者に貢献したい　など 。「自己成長」でもいいが、自分矢印のワードしか出てこないのはよくない

** 【ミッションビジョンへの共感】なぜ freee を受けたのですか？⇒この時点で強く求めているわけではない。「技術的につよそうだと思った」的な内容でも OK。その技術力をどう活かしていきたいか

** 【ユーザー志向、チーム志向】開発（または研究など）に取り組む中で、どういう風に進めていきましたか？なぜ継続して頑張れたと思いますか？どのようなゴール、理想の状態を描いていましたか？チームでの開発経験、共同作業はありますか？⇒ユーザー志向：なぜ継続して頑張れたと思うか？どのようなゴール、理想の状態を描いていたのか？ チーム志向：意見の相違はなかったか？あった際、どのように対応したのか？

**  【成長への貪欲さ】気分が乗らない（気が進まない）事柄でも頑張って取り組んだ経験はありますか？

** 【タイプ別】■ギーク：特にのめり込んだ経験はありますか？⇒程度の確認（飽きっぽくない？）■ガッツ：一番大変な思いをした経験は？⇒行動力、熱意の確認（途中で折れてない？）　■器用：一番大変な思いをした経験は？⇒筋の良さの確認（成果出せた？）
*** ギーク
『開発経験で今まで特にのめり込んだ経験はありますか？無ければ開発経験でなくても大丈夫です』
『一方で、のめり込みすぎて、納期を守れなかったことや、やるべきことをやっていなかったなど視野が狭くなっていたことはないか？また、自身で飽きっぽいと思うことはないか？』
程度の確認

*** ガッツ
『これまでの人生で一番大変な思いをした経験／壁にぶつかった経験はありましたか？』
『一方で、これまでに途中で心が折れた経験はありますか？』
行動力、熱意の確認

*** 器用
『これまでの人生で一番大変な思いをした経験／壁にぶつかった経験はありましたか？』
『最終的に自分が目指した成果は出すことができましたか？』
筋の良さの確認

** 次の面接官へ申し送りがあれば記入おねがいします
次の面接官へ申し送りがあれば記入おねがいします
回答（文章）

** リクルーター（採用チーム）へ申し送りがあれば記入おねがいします
リクルーター（採用チーム）へ申し送りがあれば記入おねがいします
回答（文章）
